version: "3.8"

services:
  database:
    image: mysql:8
    container_name: database_dev
    networks:
      - backend_network
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: book_shop_app_dev
      MYSQL_ROOT_PASSWORD: P@Word1234!!!#$#
    ports:
      - "3310:3306"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend_dev
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8080"
    networks:
      - backend_network
  web_server:
    image: nginx
    container_name: web_server_dev
    ports:
      - "9000:80"
    networks:
      - backend_network
networks:
  backend_network:
volumes:
  database_data: