version: "3.8"

services:
  database:
    image: mysql
    container_name: database_dev
    networks:
      - backend_network
    volumes:
      - database_data:/var/lib/mysql
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend_dev
    depends_on:
      - database
    networks:
      - backend_network
  web_server:
    image: nginx
    container_name: web_server_dev
    networks:
      - backend_network
networks:
  backend_network:
volumes:
  database_data: